Revert "[mlir][ODS] Use StringLiteral instead of StringRef when applicable"
This reverts commit 52b06be3d6ce89b55df2621e7d075096ce5cc47f because
it breaks GCC 5 build:

  error: could not convert '(const char*)""' from 'const char*' to 'llvm::StringLiteral'
     static ::llvm::StringLiteral getDialectNamespace() { return ""; }