Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
This reverts commit ac0ba2499a211ca4bf8b5df90aed8871fcd6b4b7.

A bot is broken